#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: e738c51
#
Name     : dvisvgm
Version  : 3.2.1
Release  : 32
URL      : https://github.com/mgieseki/dvisvgm/releases/download/3.2.1/dvisvgm-3.2.1.tar.gz
Source0  : https://github.com/mgieseki/dvisvgm/releases/download/3.2.1/dvisvgm-3.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 GPL-3.0 MIT
Requires: dvisvgm-bin = %{version}-%{release}
Requires: dvisvgm-license = %{version}-%{release}
Requires: dvisvgm-man = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-configure
BuildRequires : ghostscript-dev
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libwoff2enc)
BuildRequires : potrace-dev
BuildRequires : texlive
BuildRequires : texlive-dev
BuildRequires : xmlto
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
dvisvgm -- A DVI to SVG converter
DESCRIPTION
dvisvgm is a utility for TeX/LaTeX users. It converts DVI, EPS, and
PDF files to the XML-based scalable vector graphics format SVG.

%package bin
Summary: bin components for the dvisvgm package.
Group: Binaries
Requires: dvisvgm-license = %{version}-%{release}

%description bin
bin components for the dvisvgm package.


%package license
Summary: license components for the dvisvgm package.
Group: Default

%description license
license components for the dvisvgm package.


%package man
Summary: man components for the dvisvgm package.
Group: Default

%description man
man components for the dvisvgm package.


%prep
%setup -q -n dvisvgm-3.2.1
cd %{_builddir}/dvisvgm-3.2.1
pushd ..
cp -a dvisvgm-3.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709315534
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || true

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709315534
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dvisvgm
cp %{_builddir}/dvisvgm-%{version}/COPYING %{buildroot}/usr/share/package-licenses/dvisvgm/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/dvisvgm-%{version}/libs/boost/LICENSE.txt %{buildroot}/usr/share/package-licenses/dvisvgm/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/dvisvgm-%{version}/libs/brotli/LICENSE %{buildroot}/usr/share/package-licenses/dvisvgm/c045813a6c514f2d30d60a07c6aaf3603850e608 || :
cp %{_builddir}/dvisvgm-%{version}/libs/clipper/License.txt %{buildroot}/usr/share/package-licenses/dvisvgm/262180609d130913cbf4aacd89de9e3281fab846 || :
cp %{_builddir}/dvisvgm-%{version}/libs/variant/LICENSE.md %{buildroot}/usr/share/package-licenses/dvisvgm/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/dvisvgm-%{version}/libs/woff2/LICENSE %{buildroot}/usr/share/package-licenses/dvisvgm/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/dvisvgm-%{version}/tests/gtest/LICENSE %{buildroot}/usr/share/package-licenses/dvisvgm/5a2314153eadadc69258a9429104cd11804ea304 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/dvisvgm
/usr/bin/dvisvgm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dvisvgm/262180609d130913cbf4aacd89de9e3281fab846
/usr/share/package-licenses/dvisvgm/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/dvisvgm/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/dvisvgm/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/dvisvgm/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/dvisvgm/c045813a6c514f2d30d60a07c6aaf3603850e608

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dvisvgm.1
